// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (C) 2026 Colin Rafferty <colin@rafferty.net>

import Foundation
@testable import Schema
import Testing

struct StringMarkdownifyTest {
    @Test func allNoConvert() {
        #expect("".markdownify == nil)
        #expect("some text".markdownify == nil)
    }

    @Test func singleHref() {
        #expect("generated by <a href=\"https://raincrow.app/\">RainCrow</a>.".markdownify
            == "generated by [RainCrow](https://raincrow.app/).")
        #expect("<a href=\"https://raincrow.app/\">RainCrow</a>.".markdownify
            == "[RainCrow](https://raincrow.app/).")
        #expect("generated by <a href=\"https://raincrow.app/\">RainCrow</a>".markdownify
            == "generated by [RainCrow](https://raincrow.app/)")
    }

    @Test func multiHref() {
        #expect(
            """
            by <a href="https://raincrow.app/">RainCrow</a>.
            also <a href="https://rafferty.net/">my house</a>.
            """.markdownify
                ==
                """
                by [RainCrow](https://raincrow.app/).
                also [my house](https://rafferty.net/).
                """
        )
        #expect(
            """
            <a href="https://raincrow.app/">RainCrow</a><a href="https://rafferty.net/">my house</a>
            """.markdownify
                ==
                """
                [RainCrow](https://raincrow.app/)[my house](https://rafferty.net/)
                """
        )
    }
}
