// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (C) 2026 Colin Rafferty <colin@rafferty.net>

import Foundation
@testable import Schema
import Testing

struct StringMarkdownifyTest {
    @Test func allNoConvert() {
        #expect("".markdownify == nil)
        #expect("some text".markdownify == nil)
    }

    @Test func singleHref() {
        #expect("generated by <a href=\"https://raincrow.app/\">RainCrow</a>.".markdownify
            == "generated by [RainCrow](https://raincrow.app/).")
        #expect("<a href=\"https://raincrow.app/\">RainCrow</a>.".markdownify
            == "[RainCrow](https://raincrow.app/).")
        #expect("generated by <a href=\"https://raincrow.app/\">RainCrow</a>".markdownify
            == "generated by [RainCrow](https://raincrow.app/)")
    }

    @Test func multiHref() {
        #expect(
            """
            by <a href="https://raincrow.app/">RainCrow</a>.
            also <a href="https://rafferty.net/">my house</a>.
            """.markdownify
                ==
                """
                by [RainCrow](https://raincrow.app/).
                also [my house](https://rafferty.net/).
                """
        )
        #expect(
            """
            <a href="https://raincrow.app/">RainCrow</a><a href="https://rafferty.net/">my house</a>
            """.markdownify
                ==
                """
                [RainCrow](https://raincrow.app/)[my house](https://rafferty.net/)
                """
        )
    }

    @Test func latLng() {
        let mp = TestMarkdownProtocol()
        String.markdownProtocol = mp
        let lat = "40.67"
        let lng = "-73.97"
        let latlng = "\(lat), \(lng)"
        #expect(
            "Found it (\(latlng)).".markdownify
                ==
                "Found it ([\(latlng)](\(mp.link(lat: lat, lng: lng))))."
        )
    }

    @Test func manyLatLng() {
        let mp = TestMarkdownProtocol()
        String.markdownProtocol = mp
        let lat = "40.67"
        let lng = "-73.97"
        let latlng = "\(lat), \(lng)"
        let lnglat = "\(lng),\(lat)"
        #expect(
            "Found on (\(latlng)) and \(lnglat).".markdownify
                ==
                "Found on ([\(latlng)](\(mp.link(lat: lat, lng: lng)))) and [\(lnglat)](\(mp.link(lat: lng, lng: lat)))."
        )
    }

    @Test func both() {
        let mp = TestMarkdownProtocol()
        String.markdownProtocol = mp
        let lat = "40.67"
        let lng = "-73.97"
        let latlng = "\(lat), \(lng)"
        #expect(
            """
            Found on (\(latlng)).
            Generated by <a href="https://raincrow.app/">RainCrow</a>.
            """.markdownify
                ==
                """
                Found on ([\(latlng)](\(mp.link(lat: lat, lng: lng)))).
                Generated by [RainCrow](https://raincrow.app/).
                """
        )
    }

    @Test func unicode() {
        #expect("Getting late &#x1f622;.".markdownify == "Getting late 😢.")
    }
}

struct TestMarkdownProtocol: StringMarkdownProtocol {
    func link(lat: any StringProtocol, lng: any StringProtocol) -> String {
        "http://map/show?lat=\(lat)&lng=\(lng)"
    }
}
