// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (C) 2025 Colin Rafferty <colin@rafferty.net>

import Foundation
import Schema

extension eBirdChecklist {
    // periphery:ignore - used in #Preview
    static let fake = {
        let d = JSONDecoder()
        d.dateDecodingStrategy = .eBirdStyle
        return try! d.decode(eBirdChecklist.self, from: json)
    }()

    private static let json = """
      {
        "projId": "EBIRD",
        "subId": "S397345892",
        "protocolId": "P21",
        "locId": "L268114",
        "groupId": "G18483345",
        "durationHrs": 1.25,
        "allObsReported": true,
        "comments": "Hummingbird numbers conservatively estimated. \\n\\n+Rock Squirrel\\n\\n⛅️☁️\\nScattered clouds - broken clouds\\nTemperature: 75°F\\nWind: Light breeze - gentle breeze\\nWind Direction: W - SW\\nCloud Cover: 48 - 65%\\nHumidity: 39 - 42%\\nDew point: 49 - 50°F\\nSunrise: 6:15am\\nSunset: 6:12pm\\nWeather generated by <a href=\\"https://raincrow.app/\\">RainCrow</a>",
        "creationDt": "2026-09-28 22:36",
        "lastEditedDt": "2026-10-01 09:27",
        "obsDt": "2026-09-28 13:49",
        "obsTimeValid": true,
        "checklistId": "CL26433",
        "numObservers": 3,
        "effortAreaEnteredUnit": "ac",
        "subnational1Code": "US-AZ",
        "submissionMethodCode": "EBIRD_iOS",
        "submissionMethodVersion": "3.7.23",
        "deleteTrack": false,
        "userDisplayName": "Nell Smith",
        "numSpecies": 16,
        "submissionMethodVersionDisp": "3.7.23",
        "subAux": [
          {
            "subId": "S397345892",
            "fieldName": "nocturnal",
            "entryMethodCode": "ebird_nocturnal",
            "auxCode": "0"
          }
        ],
        "subAuxAi": [
          {
            "subId": "S397345892",
            "method": "concurrent",
            "aiType": "sound",
            "source": "merlin",
            "eventId": 0
          }
        ],
        "projectIds": [],
        "obs": [
          {
            "speciesCode": "moudov",
            "howManyAtleast": 3,
            "howManyAtmost": 3,
            "present": false,
            "obsId": "OBS4920688791",
            "howManyStr": "3"
          },
          {
            "speciesCode": "vauswi",
            "howManyAtleast": 3,
            "howManyAtmost": 3,
            "comments": "Three individual birds seen at once flying moderately high in the canyon ~3pm. Pale underneath, lacking the contrasting white throat and rump patches of a WTSW and shorter wings.",
            "present": false,
            "obsId": "OBS4920688793",
            "howManyStr": "3",
            "mediaCounts": {
              "P": 2
            }
          },
          {
            "speciesCode": "maghum1",
            "howManyAtleast": 3,
            "howManyAtmost": 3,
            "comments": "As magnificent as always!",
            "present": false,
            "obsId": "OBS4920688779",
            "howManyStr": "3"
          },
          {
            "speciesCode": "bkchum",
            "howManyAtleast": 8,
            "howManyAtmost": 8,
            "present": false,
            "obsId": "OBS4920688788",
            "howManyStr": "8"
          },
          {
            "speciesCode": "annhum",
            "howManyAtleast": 6,
            "howManyAtmost": 6,
            "present": false,
            "obsId": "OBS4920688785",
            "howManyStr": "6"
          },
          {
            "speciesCode": "brbhum",
            "howManyAtleast": 5,
            "howManyAtmost": 5,
            "present": false,
            "obsId": "OBS4920688786",
            "howManyStr": "5"
          },
          {
            "speciesCode": "acowoo",
            "howManyAtleast": 7,
            "howManyAtmost": 7,
            "present": false,
            "obsId": "OBS4920688781",
            "howManyStr": "7"
          },
          {
            "speciesCode": "mexjay4",
            "howManyAtleast": 8,
            "howManyAtmost": 8,
            "present": false,
            "obsId": "OBS4920688787",
            "howManyStr": "8"
          },
          {
            "speciesCode": "britit",
            "howManyAtleast": 1,
            "howManyAtmost": 1,
            "present": false,
            "obsId": "OBS4920688792",
            "howManyStr": "1"
          },
          {
            "speciesCode": "whbnut3",
            "howManyAtleast": 2,
            "howManyAtmost": 2,
            "present": false,
            "obsId": "OBS4920688782",
            "howManyStr": "2"
          },
          {
            "speciesCode": "houwre",
            "howManyAtleast": 1,
            "howManyAtmost": 1,
            "present": false,
            "obsId": "OBS4920688789",
            "howManyStr": "1"
          },
          {
            "speciesCode": "bewwre",
            "howManyAtleast": 1,
            "howManyAtmost": 1,
            "present": false,
            "obsId": "OBS4920688784",
            "howManyStr": "1"
          },
          {
            "speciesCode": "cedwax",
            "howManyAtleast": 1,
            "howManyAtmost": 1,
            "present": false,
            "obsId": "OBS4920688794",
            "howManyStr": "1"
          },
          {
            "speciesCode": "houfin",
            "howManyAtleast": 6,
            "howManyAtmost": 6,
            "present": false,
            "obsId": "OBS4920688780",
            "howManyStr": "6"
          },
          {
            "speciesCode": "lesgol",
            "howManyAtleast": 2,
            "howManyAtmost": 2,
            "present": false,
            "obsId": "OBS4920688790",
            "howManyStr": "2"
          },
          {
            "speciesCode": "paired",
            "howManyAtleast": 1,
            "howManyAtmost": 1,
            "present": false,
            "obsId": "OBS4920688783",
            "howManyStr": "1"
          }
        ]
      }
    """.data(using: .utf8)!
}
